// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhBUVucJ0aWn29Q3qrugxG1Lb0dCnHtk4',
    appId: '1:456728648825:web:c502da082a9da1bfb748a8',
    messagingSenderId: '456728648825',
    projectId: 'user-database-promact',
    authDomain: 'user-database-promact.firebaseapp.com',
    storageBucket: 'user-database-promact.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUyzPWJoq8LH5_gzPkrVgTKojhxj0oZHw',
    appId: '1:456728648825:android:9cc00ef0b60f0b6ab748a8',
    messagingSenderId: '456728648825',
    projectId: 'user-database-promact',
    storageBucket: 'user-database-promact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGv_ASiq06kjA6q4cvlrGCcx9JjpGuS18',
    appId: '1:456728648825:ios:6abc239d148b9f26b748a8',
    messagingSenderId: '456728648825',
    projectId: 'user-database-promact',
    storageBucket: 'user-database-promact.appspot.com',
    iosClientId: '456728648825-j9fjjeqnkoevr8il44hsjnsh26slh54u.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGv_ASiq06kjA6q4cvlrGCcx9JjpGuS18',
    appId: '1:456728648825:ios:6abc239d148b9f26b748a8',
    messagingSenderId: '456728648825',
    projectId: 'user-database-promact',
    storageBucket: 'user-database-promact.appspot.com',
    iosClientId: '456728648825-j9fjjeqnkoevr8il44hsjnsh26slh54u.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );
}
